# Generated by Django 3.0.5 on 2020-04-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.Ship')),
            ],
        ),
        migrations.CreateModel(
            name='FW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.Ship')),
            ],
        ),
    ]
